# permissions for end users to edit metrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metric-editor-role
rules:
- apiGroups:
  - iter8.tools
  resources:
  - metrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iter8.tools
  resources:
  - metrics/status
  verbs:
  - get
