# permissions for end users to view metrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metric-viewer-role
rules:
- apiGroups:
  - iter8.tools
  resources:
  - metrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iter8.tools
  resources:
  - metrics/status
  verbs:
  - get
