# These roles will used by the controller and handlers
# controllers are bound to roles: experiments, metrics and jobs
# handlers are only bound to roles: experiments and metrics
# additional roles and rolebindings come from domain package(s)
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: experiments
rules:
- apiGroups:
  - iter8.tools
  resources:
  - experiments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iter8.tools
  resources:
  - experiments/status
  verbs:
  - get
  - patch
  - update
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metrics
rules:
- apiGroups:
  - iter8.tools
  resources:
  - metrics
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jobs
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
