name: Additional tests for iter8ctl

on:
  push:
    branches:
      - main # Publish `main` as Docker `latest` image.
  pull_request: # Run tests for any PRs.

jobs:
  test-iter8ctl:
    strategy:
      matrix:
        go-version: [1.16.x,1.17.x]
        os: [macos-latest] ## did ubuntu-latest in build-and-test job 
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}        
    - name: Set up Kubebuilder 3.1.0
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)

        # download kubebuilder and extract it to tmp
        curl -L -o kubebuilder https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_$(go env GOOS)_$(go env GOARCH)
        chmod +x kubebuilder && mv kubebuilder /usr/local/bin/
        export PATH=$PATH:/usr/local/kubebuilder/bin
    - name: Checkout code
      uses: actions/checkout@v2
    ## Ran staticcheck, vet, lint in build-and-test job
    - name: Test
      run: make test-iter8ctl